package Exception.Finally;

public class Throw {

//    public static void main(String[] args) {
//        try{
//            int x = method();
//        }
//    }
//
//    private static int method() {
//        if ( 2/3 == 0){
//            throw new RuntimeException("blahhh");
//            return 10;
//        }
//        else return 30;
//    }
}
